apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-demo
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: devops-demo

  namespaceSelector:
    matchNames:
      - devops-demo

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
