apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-demo-app
  namespace: devops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-demo-app

  template:
    metadata:
      labels:
        app: devops-demo-app

    spec:
      containers:
      - name: devops-demo
        image: samirsomer/devops-demo-app

        envFrom:
        - configMapRef:
            name: devops-demo-config

        ports:
        - containerPort: 8000

        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
